version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    networks:
      - external-network

    
networks:
  external-network:
    external:
      name: external_network
