@clientId=device-auth

### device auth
POST http://host.docker.internal:8080/realms/poc/protocol/openid-connect/auth/device
Content-Type: application/x-www-form-urlencoded

&client_id={{clientId}}


### get token after verification is done in a browser
POST http://host.docker.internal:8080/realms/poc/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

&client_id={{clientId}}
&device_code=B3DS9puPGa4UU_7ngiG30KJbOPMT2nrgMKaiqGivrv0
&grant_type=urn:ietf:params:oauth:grant-type:device_code


### if user has no active session
GET http://host.docker.internal:8080/realms/poc/device?user_code=RFJS-WXFT
