@token=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhNGUzZWZlYS1iODhlLTRjNTItYWNiNi1kMGU0NWJhMGYxZDAifQ.eyJleHAiOjE3MjA1NDQyNTYsImlhdCI6MTcyMDU0MjQ1NiwianRpIjoiMDRjYjY5MDctZDU0NS00MjY2LTg2OGMtMGM0OWUwYzQyYTY2IiwiaXNzIjoiaHR0cDovL2hvc3QuZG9ja2VyLmludGVybmFsOjgwODAvcmVhbG1zL3BvYyIsImF1ZCI6Imh0dHA6Ly9ob3N0LmRvY2tlci5pbnRlcm5hbDo4MDgwL3JlYWxtcy9wb2MiLCJzdWIiOiJkNGY3ZTA0Ny1hZDZhLTRlZjQtOWYwOS01NTA3NzlmZTdjYmQiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoicG9jIiwic2Vzc2lvbl9zdGF0ZSI6IjJiNTc1YzA3LTM2NDctNGZiNC1hYzJjLWQwMmViMjYzNGQzZiIsInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiIyYjU3NWMwNy0zNjQ3LTRmYjQtYWMyYy1kMDJlYjI2MzRkM2YifQ.qRIzCO4Rf_7Ea8kJ5EnJExWiKF3luPQzPBvYTJTUzDs
@authToken=Bearer {{token}}
@clientId=poc
@clientSecret=

###
POST http://localhost:3000/create-qr-code
Content-Type: application/json
Authorization: {{authToken}}


###
GET http://localhost:3000/scan-qr-code


###
POST http://localhost:3000/introspect


### Introspect Token
POST http://host.docker.internal:8080/realms/poc/protocol/openid-connect/token/introspect
Content-Type: application/x-www-form-urlencoded
Header: localhost

token={{token}}
&client_id={{clientId}}
&client_secret={{clientSecret}}


### get token by refresh token
POST http://host.docker.internal:8080/realms/poc/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Header: localhost

refresh_token={{token}}
&grant_type=refresh_token
&client_id={{clientId}}
&client_secret={{clientSecret}}
